name: Use the Composite Actions with Actions

on: 
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      
      - name: Do Anything else
        run: echo pretend to do other things
        
        
      - name: Build and Push the Image
        uses: udaynalluri/CompositeActions
        with: 
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERTOKEN }}
          image_name: my-new-app
          tag: $GITHUB_RUN_NUMBER
          
